spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/recipevault
    username: recipevault_user
    password: recipevault_pass

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    validate-on-migrate: true

logging:
  level:
    com.vadovates.app: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG